src/objects/Salsa_Data_Import__c.object
<CustomObject>
    <fields>
        <fullName>Entered_Email__c</fullName>
        <label>Entered Email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Error_Code__c</fullName>
        <label>Error Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Validated_Email__c</fullName>
        <inlineHelpText>Validated Entered Email as correct format</inlineHelpText>
        <label>Validated Email</label>
        <type>Email</type>
    </fields>
    <label>Salsa Data Import</label>
    <nameField>
        <displayFormat>SDI-{00000}</displayFormat>
        <label>Salsa Data Import Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Salsa Data Imports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ManageSalsaImports.cls
public with sharing class ManageSalsaImports {

public static void beforeInsert(Salsa_Data_Import__c[] newrecords) {

for (Salsa_Data_Import__c sdi: newrecords) {
    if (sdi.Entered_Email__c != null) {

            if (Utilities_BFC.checkEmail(sdi.Entered_Email__c) ) {
                    sdi.Validated_Email__c = sdi.Entered_Email__c;    
            }
            else {
                    sdi.Error_Code__c = 'Bad Email';
            }
    } //end email check

    if (sdi.Phone__c != null) {
            sdi.Phone__c = Utilities_bfc.formatphonenumber(sdi.Phone__c);
    }

} //end loop    

} //end method

} //end class